# Generated by Django 2.0 on 2018-05-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_auto_20180426_2142'),
        ('read_statistics', '0003_auto_20180427_0849'),
    ]

    operations = [
    ]
