# Generated by Django 2.0 on 2018-05-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_merge_20180430_2059'),
        ('blog', '0008_auto_20180427_0849'),
    ]

    operations = [
    ]
