# Generated by Django 2.0 on 2018-04-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180407_1945'),
        ('comment', '0002_auto_20180407_1751'),
    ]

    operations = [
    ]
