# Generated by Django 2.0 on 2018-04-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20180427_1739'),
        ('comment', '0007_auto_20180426_2142'),
    ]

    operations = [
    ]
